apiVersion: v1 # The API version for Service object
kind: Service # the type of object to create
metadata:
  name: excellent-bookshop # name of the service (must be a valid DNS name)
  labels:
    app: excellent-bookshop # a label attached to the Service
spec:
  type: ClusterIP  # Type of service
  selector:
    app: excellent-bookshop # the label used to match the pods to target and expose
  ports:
    - protocol: TCP # network protocol used by the Service
      port: 80 # The port exposed by the Service
      targetPort: 9001 # the port exposed by the Pods targeted by the Service
