#name of the workflow
name: Commit Stage

# the workflow is triggered when new code is published to the repository
on: push

env:
  REGISTRY: ghcr.io  # uses the GiyHub container registry
  IMAGE_NAME: chiskien/excellent-bookshop # the github-name/image-name
  VERSION: latest

jobs:
  build: #the job's unique identifier
    name: Build and Test # human-friendly name for the job
    runs-on: ubuntu-22.04 # the type of machine where the job should be run
    permissions: # the permissions granted to the job
      contents: read #Permission to check out the current Git repository
      security-events: write # Permission to submit security events to GitHub
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3 # check out the current repository
      - name: Set up JDK
        uses: actions/setup-java@v3   # installs and configures JRE
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests, and integration tests
        run: mvn --batch-mode --update-snapshots package

  package: # The job's unique identifier
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/master' }} # runs job only on primary branch
    needs: [ build ]  # runs job only if the "build" successfully
    runs-on: ubuntu-22.04 # base image
    permissions:
      contents: read   #Permission to check out the current Git repository
      packages: write #Permission to upload images to GitHub Container Registry
      security-events: write # Permission to submit security events to GitHub
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build container image
        # using BuildPacks integration in Spring to build container image
        # and using property from "env" at line 7
        run: mvn spring-boot:build-image -D imageName=${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.VERSION}}

      - name: OCI Image vulnerability scanning # scan the release candidate image for vulnerabilities using Grype
        uses: anchore/scan-action@v3
        id: scan
        with:
          # image to be scanned
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          fail-build: false # won't fail the build if vulnerable is found
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2 # uploads the security vulnerability report to GitHub
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Log into container registry
        uses: docker/login-action@v2  # authenticates with GitHub Container Registry
        with:
          registry: ${{ env.REGISTRY }} # The registry value as defined in the environment variable earlier
          username: ${{ github.actor }} # The GitHub username of the current user, provided by GitHub Actions
          password: ${{ secrets.GITHUB_TOKEN }} # The token needed to authenticate with the registry, provided by GitHub Actions
      - name: Publish container image # Pushes the release candidate to the registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
